In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [2]:
data_frame = pd.read_csv("../dataset/loan_approval_dataset.csv",)

In [3]:
data_frame

loan_id   no_of_dependents      education  self_employed   income_annum   
0           1                  2       Graduate             No        9600000  \
1           2                  0   Not Graduate            Yes        4100000   
2           3                  3       Graduate             No        9100000   
3           4                  3       Graduate             No        8200000   
4           5                  5   Not Graduate            Yes        9800000   
...       ...                ...            ...            ...            ...   
4264     4265                  5       Graduate            Yes        1000000   
4265     4266                  0   Not Graduate            Yes        3300000   
4266     4267                  2   Not Graduate             No        6500000   
4267     4268                  1   Not Graduate             No        4100000   
4268     4269                  1       Graduate             No        9200000   

       loan_amount   loan_term   cibil_score   residential_assets_value   
0         29900000          12           778                    2400000  \
1         12200000           8           417                    2700000   
2         29700000          20           506                    7100000   
3         30700000           8           467                   18200000   
4         24200000          20           382                   12400000   
...            ...         ...           ...                        ...   
4264       2300000          12           317                    2800000   
4265      11300000          20           559                    4200000   
4266      23900000          18           457                    1200000   
4267      12800000           8           780                    8200000   
4268      29700000          10           607                   17800000   

       commercial_assets_value   luxury_assets_value   bank_asset_value   
0                     17600000              22700000            8000000  \
1                      2200000               8800000            3300000   
2                      4500000              33300000           12800000   
3                      3300000              23300000            7900000   
4                      8200000              29400000            5000000   
...                        ...                   ...                ...   
4264                    500000               3300000             800000   
4265                   2900000              11000000            1900000   
4266                  12400000              18100000            7300000   
4267                    700000              14100000            5800000   
4268                  11800000              35700000           12000000   

      loan_status  
0        Approved  
1        Rejected  
2        Rejected  
3        Rejected  
4        Rejected  
...           ...  
4264     Rejected  
4265     Approved  
4266     Rejected  
4267     Approved  
4268     Approved  

[4269 rows x 13 columns]

In [4]:
data_frame.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   loan_id                    4269 non-null   int64 
 1    no_of_dependents          4269 non-null   int64 
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64 
 5    loan_amount               4269 non-null   int64 
 6    loan_term                 4269 non-null   int64 
 7    cibil_score               4269 non-null   int64 
 8    residential_assets_value  4269 non-null   int64 
 9    commercial_assets_value   4269 non-null   int64 
 10   luxury_assets_value       4269 non-null   int64 
 11   bank_asset_value          4269 non-null   int64 
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB


In [5]:
data_frame.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [6]:
label_encoder = LabelEncoder()
data_frame[' self_employed'] = label_encoder.fit_transform(data_frame[' self_employed'].str.lower())
# data_frame['education'] = label_encoder.fit_transform(data_frame[' education'].str.lower())
# data_frame['loan_status'] = label_encoder.fit_transform(data_frame[' loan_status'].str.lower())

In [7]:
data_frame[' education'] = label_encoder.fit_transform(data_frame[' education'].str.lower())

In [8]:
data_frame[' loan_status'] = label_encoder.fit_transform(data_frame[' loan_status'].str.lower())

In [9]:
data_frame

loan_id   no_of_dependents   education   self_employed   income_annum   
0           1                  2           0               0        9600000  \
1           2                  0           1               1        4100000   
2           3                  3           0               0        9100000   
3           4                  3           0               0        8200000   
4           5                  5           1               1        9800000   
...       ...                ...         ...             ...            ...   
4264     4265                  5           0               1        1000000   
4265     4266                  0           1               1        3300000   
4266     4267                  2           1               0        6500000   
4267     4268                  1           1               0        4100000   
4268     4269                  1           0               0        9200000   

       loan_amount   loan_term   cibil_score   residential_assets_value   
0         29900000          12           778                    2400000  \
1         12200000           8           417                    2700000   
2         29700000          20           506                    7100000   
3         30700000           8           467                   18200000   
4         24200000          20           382                   12400000   
...            ...         ...           ...                        ...   
4264       2300000          12           317                    2800000   
4265      11300000          20           559                    4200000   
4266      23900000          18           457                    1200000   
4267      12800000           8           780                    8200000   
4268      29700000          10           607                   17800000   

       commercial_assets_value   luxury_assets_value   bank_asset_value   
0                     17600000              22700000            8000000  \
1                      2200000               8800000            3300000   
2                      4500000              33300000           12800000   
3                      3300000              23300000            7900000   
4                      8200000              29400000            5000000   
...                        ...                   ...                ...   
4264                    500000               3300000             800000   
4265                   2900000              11000000            1900000   
4266                  12400000              18100000            7300000   
4267                    700000              14100000            5800000   
4268                  11800000              35700000           12000000   

       loan_status  
0                0  
1                1  
2                1  
3                1  
4                1  
...            ...  
4264             1  
4265             0  
4266             1  
4267             0  
4268             0  

[4269 rows x 13 columns]

In [10]:
data_frame.columns=['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       ' luxury_assets_value', 'bank_asset_value', 'loan_status']

In [11]:
data_frame.columns

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       ' luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='object')

In [12]:
data_frame['self_employed'].unique()

array([0, 1])

In [13]:
data_frame['education'].unique()

array([0, 1])

In [14]:
data_frame.loan_status.unique()

array([0, 1])

In [15]:
data_frame.no_of_dependents.unique()

array([2, 0, 3, 5, 4, 1], dtype=int64)

In [16]:
data_frame.income_annum.unique()
len(data_frame.income_annum.unique())

98

In [17]:
len(data_frame.loan_amount.unique())

378

In [18]:
data_frame.loan_term.unique()

array([12,  8, 20, 10,  4,  2, 18, 16, 14,  6], dtype=int64)

In [19]:
x = data_frame.drop(['loan_status','loan_id'],axis=1)
x

no_of_dependents  education  self_employed  income_annum  loan_amount   
0                    2          0              0       9600000     29900000  \
1                    0          1              1       4100000     12200000   
2                    3          0              0       9100000     29700000   
3                    3          0              0       8200000     30700000   
4                    5          1              1       9800000     24200000   
...                ...        ...            ...           ...          ...   
4264                 5          0              1       1000000      2300000   
4265                 0          1              1       3300000     11300000   
4266                 2          1              0       6500000     23900000   
4267                 1          1              0       4100000     12800000   
4268                 1          0              0       9200000     29700000   

      loan_term  cibil_score  residential_assets_value   
0            12          778                   2400000  \
1             8          417                   2700000   
2            20          506                   7100000   
3             8          467                  18200000   
4            20          382                  12400000   
...         ...          ...                       ...   
4264         12          317                   2800000   
4265         20          559                   4200000   
4266         18          457                   1200000   
4267          8          780                   8200000   
4268         10          607                  17800000   

      commercial_assets_value   luxury_assets_value  bank_asset_value  
0                    17600000              22700000           8000000  
1                     2200000               8800000           3300000  
2                     4500000              33300000          12800000  
3                     3300000              23300000           7900000  
4                     8200000              29400000           5000000  
...                       ...                   ...               ...  
4264                   500000               3300000            800000  
4265                  2900000              11000000           1900000  
4266                 12400000              18100000           7300000  
4267                   700000              14100000           5800000  
4268                 11800000              35700000          12000000  

[4269 rows x 11 columns]

In [20]:
y = data_frame['loan_status'].values
y

array([0, 1, 1, ..., 1, 0, 0])

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=41)

In [22]:
scaler = StandardScaler()

In [23]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled =scaler.transform(x_test)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import pickle
import warnings
model = LogisticRegression()
model.fit(x_train_scaled,y_train)
print(f"Fitting score of the model is {model.score(x_train_scaled,y_train)}")



Fitting score of the model is 0.927086383601757


x_train ->(3415, 11)
y_train ->(3415,)
x_test->(854, 11)
y_test->(854,)

In [25]:
#Predicting from the model

y_pred = model.predict(x_test_scaled)

f1_Score = metrics.f1_score(y_pred,y_test)
print(f"R2 score is {f1_Score}")

R2 score is 0.8584758942457231


In [26]:
new_intsance = np.array([1,1,1,9100000,24000000,11,653,5500000,6800000,1400000,6600000])
new = new_intsance.reshape(-1,1)
new = new.T
print(new)

[[       1        1        1  9100000 24000000       11      653  5500000
   6800000  1400000  6600000]]


In [27]:
data_frame.iloc[0,:]

loan_id                            1
no_of_dependents                   2
education                          0
self_employed                      0
income_annum                 9600000
loan_amount                 29900000
loan_term                         12
cibil_score                      778
residential_assets_value     2400000
commercial_assets_value     17600000
 luxury_assets_value        22700000
bank_asset_value             8000000
loan_status                        0
Name: 0, dtype: int64

In [28]:
scaled_data = scaler.transform(new)
prediction = model.predict(scaled_data)
print(prediction[0])

0


c:\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [29]:
second_instance=np.array([1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000])
second = second_instance.reshape(-1,1).T
#second_scaled =  scaler.transform(second)
#print(second_scaled)
prediction_second = model.predict(second)

print(prediction_second[0])


0


In [30]:
x_train.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', ' luxury_assets_value', 'bank_asset_value'],
      dtype='object')

In [58]:
second_instance=np.array([5,1,1,9800000,24200000,20,350,1240000,820000,2940000,4000000])
second = second_instance.reshape(-1,1).T
second_scaled =  scaler.transform(second)
print(second_scaled)
prediction_second = model.predict(second_scaled)
if(second_scaled[0][6]<300):
    prediction_second[0] = 0
print(prediction_second[0])


[[ 1.46981786  1.01326513  0.98402221  1.68775087  1.00457542  1.59292292
  -1.45617254 -0.95780323 -0.94378244 -1.33811022 -0.29820135]]
0


c:\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [64]:
#Test case 1
# Dependents- 8
# Not graduated 
# Self employed 
# Income - 300000
# Loan amt - 5000000
# Term - 4
# Cibil - 350
# Assets 10000, 50000, 20000, 100000
first_instance=np.array([8,1,1,300000,5000000,4,350,10000,50000,20000,100000])
first = first_instance.reshape(-1,1).T
first_scaled =  scaler.transform(first)
print(first_scaled)
prediction = model.predict(first_scaled)

if prediction[0]==0:
    print(f"Loan approved")
else:
    print("loan rejected")


[[ 3.2355641   1.01326513  0.98402221 -1.69867972 -1.12115195 -1.20516453
  -1.45617254 -1.14788815 -1.11820773 -1.6588257  -1.50507951]]
loan rejected


c:\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [67]:
# #Test case 2
# Dependents- 4
#  graduated 
# Self employed 
# Income - 3000000
# Loan amt - 10000000
# Term - 6
# Cibil - 800
# Assets 100000, 500000, 200000, 1000000
second_instance=np.array([4,0,1,3000000,10000000,6,800,100000,500000,200000,1000000])
second = second_instance.reshape(-1,1).T
second_scaled =  scaler.transform(second)
print(second_scaled)
prediction = model.predict(second_scaled)
print(type(prediction[0]))
if prediction[0] == 0:
    print(f"Loan approved")
else:
    print("loan rejected")


[[ 0.88123578 -0.98690853  0.98402221 -0.7362205  -0.56757712 -0.8554036
   1.16337934 -1.1339795  -1.01627087 -1.63905557 -1.22656916]]
<class 'numpy.int32'>
Loan approved


c:\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [68]:
# #Test case 3
# Dependents- 3
# graduated 
# employed 
# Income - 1500000
# Loan amt - 5000000
# Term - 5
# Cibil - 600
# Assets 200000, 600000, 100000, 1500000
third_instance=np.array([3,0,1,1500000,5000000,5,600,200000,600000,100000,1500000])
second = second_instance.reshape(-1,1).T
second_scaled =  scaler.transform(second)
print(second_scaled)
prediction = model.predict(second_scaled)
print(type(prediction[0]))
if prediction[0] == 0:
    print(f"Loan approved")
else:
    print("loan rejected")


[[ 0.88123578 -0.98690853  0.98402221 -0.7362205  -0.56757712 -0.8554036
   1.16337934 -1.1339795  -1.01627087 -1.63905557 -1.22656916]]
<class 'numpy.int32'>
Loan approved


c:\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
